title: Richie Doherty # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software delivery expert and Appian Developer by day, hockey data science enthusiast by night. I have found a great joy in applying my data science skills to my life long passion of hockey. 
  <br><br>
  I'm always interested in growing my craft, please reach out to me with any questions you have about my projects, or any interesting opportunties you want to explore.  
  <br><br>
  <a href="https://www.linkedin.com/in/rdoherty10/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
