title: Richie Doherty # your name (or website title) here
logo: "images/IMG_2483.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software delivery expert: Appian Developer by day, hockey data science enthusiast by night. Applying my data science skills to my life long passion of hockey. 
  <br><br>
  Please reach out to me with any questions you have about my projects, or any interesting opportunties you want to explore.  
  <br><br>
  <a href="https://www.linkedin.com/in/rdoherty10/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-NDE18PZP26 # your Google Analytics tracking ID here
